In [129]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import yaml
import json
import random
import math
from supabase import create_client, Client
import csv

seq_len = 10
generate_until = 10000

In [130]:
url = "https://glhuwccllsesgbzkzjad.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaHV3Y2NsbHNlc2diemt6amFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg0MDA5MTUsImV4cCI6MTk4Mzk3NjkxNX0._1H080LNXOEr7v19AwYTVBdFMWERI9yCxuLFYbSl1sg"
supabase: Client = create_client(url, key)

In [131]:
data = supabase.table("interactions").select("*").execute()
data = json.loads(data.json())
data = pd.DataFrame(data["data"])

print(data.shape)
data.head()

(39, 9)


id  user_id  question_id lecture_id  content_id  user_answer  \
0  1669179545274        0            0       None           0            3   
1  1669179559079        0            1       None           1            1   
2  1669179570936        0            2       None           2            0   
3  1669179578181        0            3       None           3            1   
4  1669179588565        1            0       None           0            2   

   answered_correctly  elapsed_time  concept_id  
0                   1            17           1  
1                   1            13           1  
2                   0            11           0  
3                   1             7           0  
4                   0             5           1

In [132]:
questions = supabase.table("questions").select("*").execute()
questions = json.loads(questions.json())
questions = pd.DataFrame(questions["data"])

print(questions.shape)
questions.head()

(10, 6)


id                 created_at  concept  correct_answer        question  \
0   0  2022-11-23T04:58:07+00:00        1               3  What is 11*11?   
1   1  2022-11-23T04:57:33+00:00        1               1   What is 3*12?   
2   2  2022-11-23T04:53:47+00:00        0               2  What is 11+12?   
3   3  2022-11-20T03:26:31+00:00        0               1  What is 2 + 4?   
4   4  2022-11-27T22:48:07+00:00        2               2         2x = 20   

                          answers  
0               [90, 11, 13, 121]  
1               [312, 36, 48, 12]  
2              [1112, 13, 23, 33]  
3                   [24, 6, 4, 2]  
4  [x = 2, x = 20, x = 10, x = 5]

In [133]:
concepts = supabase.table("concepts").select("*").execute()
concepts = json.loads(concepts.json())
concepts = pd.DataFrame(concepts["data"])

print(concepts.shape)
concepts.head()

(3, 3)


id                 created_at            name
0   0  2022-11-15T17:08:53+00:00        addition
1   1  2022-11-23T04:57:00+00:00  multiplication
2   2  2022-11-27T22:47:07+00:00       equations

In [134]:
for i, row in questions.iterrows():
    interactions = data[data["question_id"] == row["id"]]
    sum_correct = 0

    for j, interaction in interactions.iterrows():
        if interaction["answered_correctly"] == 1:
            sum_correct += 1

    questions.at[i, "difficulty"] = sum_correct / len(interactions)

print(questions.shape)
questions.head()

(10, 7)


id                 created_at  concept  correct_answer        question  \
0   0  2022-11-23T04:58:07+00:00        1               3  What is 11*11?   
1   1  2022-11-23T04:57:33+00:00        1               1   What is 3*12?   
2   2  2022-11-23T04:53:47+00:00        0               2  What is 11+12?   
3   3  2022-11-20T03:26:31+00:00        0               1  What is 2 + 4?   
4   4  2022-11-27T22:48:07+00:00        2               2         2x = 20   

                          answers  difficulty  
0               [90, 11, 13, 121]       0.500  
1               [312, 36, 48, 12]       0.625  
2              [1112, 13, 23, 33]       0.375  
3                   [24, 6, 4, 2]       1.000  
4  [x = 2, x = 20, x = 10, x = 5]       0.500

In [135]:
data = data.sample(frac=1).reset_index(drop=True)
print(data.shape)
data.head()

(39, 9)


id  user_id  question_id lecture_id  content_id  user_answer  \
0  1669588695272        1            2       None           2            3   
1  1669589741230        1            8       None           8            1   
2  1669588819420        1            3       None           3            1   
3  1669588676588        0            1       None           1            2   
4  1669588671010        0            2       None           2            2   

   answered_correctly  elapsed_time  concept_id  
0                   0             4           0  
1                   1             2           0  
2                   1             2           0  
3                   0             5           1  
4                   1             7           0

In [136]:
offset = data["concept_id"].max() + 1

for i, row in data.iterrows():
    data.at[i, "question_id"] = row["question_id"] + offset

data.head()

id  user_id  question_id lecture_id  content_id  user_answer  \
0  1669588695272        1            5       None           2            3   
1  1669589741230        1           11       None           8            1   
2  1669588819420        1            6       None           3            1   
3  1669588676588        0            4       None           1            2   
4  1669588671010        0            5       None           2            2   

   answered_correctly  elapsed_time  concept_id  
0                   0             4           0  
1                   1             2           0  
2                   1             2           0  
3                   0             5           1  
4                   1             7           0

In [137]:
val_size = int(data.shape[0] * 0.2)

val = data[-val_size:]
train = data[:-val_size]

In [138]:
train_dict = {}
val_dict = {}

for i, row in train.iterrows():
    if row["user_id"] not in train_dict:
        train_dict[row["user_id"]] = [
            0,
            [],
            [],
            []
        ]
    train_dict[row["user_id"]][0] += 1
    train_dict[row["user_id"]][1].append(int(row["concept_id"]))
    train_dict[row["user_id"]][2].append(int(row["question_id"]))
    if int(row["answered_correctly"]) == 1:
        train_dict[row["user_id"]][3].append(53331)
    else:
        train_dict[row["user_id"]][3].append(53330)

for i, row in val.iterrows():
    if row["user_id"] not in val_dict:
        val_dict[row["user_id"]] = [
            0,
            [],
            [],
            []
        ]
    val_dict[row["user_id"]][0] += 1
    val_dict[row["user_id"]][1].append(int(row["concept_id"]))
    val_dict[row["user_id"]][2].append(int(row["question_id"]))
    if int(row["answered_correctly"]) == 1:
        val_dict[row["user_id"]][3].append(53331)
    else:
        val_dict[row["user_id"]][3].append(53330)

In [139]:
val_dict

{0: [5, [1, 0, 0, 2, 2], [4, 5, 5, 9, 7], [53331, 53330, 53330, 53330, 53331]],
 1: [2, [1, 0], [4, 5], [53330, 53331]]}

In [140]:
train_path = "data/custom/custom_train.csv"
val_path = "data/custom/custom_test.csv"

with open(train_path, "w") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_NONE,
                        escapechar=" ", delimiter=" ")

    for key in train_dict:
        arr = train_dict[key]

        for data in arr:
            if type(data) == list:
                writer.writerow([",".join([str(x) for x in data])])
            else:
                writer.writerow([data])

with open(val_path, "w") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_NONE,
                        escapechar=" ", delimiter=" ")

    for key in val_dict:
        arr = val_dict[key]

        for data in arr:
            if type(data) == list:
                writer.writerow([",".join([str(x) for x in data])])
            else:
                writer.writerow([data])


In [141]:
skill_matrix = np.zeros((len(concepts), len(concepts)), dtype=int)

for i, row in concepts.iterrows():
    skill_matrix[i][i] = 1

print(skill_matrix)

np.savetxt("data/custom/custom_skill_matrix.txt", skill_matrix, delimiter=" ", fmt="%d")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
