In [89]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import yaml
import json
import random
import math
from supabase import create_client, Client
import csv

seq_len = 10
generate_until = 10000

In [90]:
url = "https://glhuwccllsesgbzkzjad.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaHV3Y2NsbHNlc2diemt6amFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg0MDA5MTUsImV4cCI6MTk4Mzk3NjkxNX0._1H080LNXOEr7v19AwYTVBdFMWERI9yCxuLFYbSl1sg"
supabase: Client = create_client(url, key)

In [91]:
data = supabase.table("interactions").select("*").execute()
data = json.loads(data.json())
data = pd.DataFrame(data["data"])

print(data.shape)
data.head()

(39, 9)


id  user_id  question_id lecture_id  content_id  user_answer  \
0  1669179545274        0            0       None           0            3   
1  1669179559079        0            1       None           1            1   
2  1669179570936        0            2       None           2            0   
3  1669179578181        0            3       None           3            1   
4  1669179588565        1            0       None           0            2   

   answered_correctly  elapsed_time  concept_id  
0                   1            17           1  
1                   1            13           1  
2                   0            11           0  
3                   1             7           0  
4                   0             5           1

In [92]:
questions = supabase.table("questions").select("*").execute()
questions = json.loads(questions.json())
questions = pd.DataFrame(questions["data"])

print(questions.shape)
questions.head()

(10, 6)


id                 created_at  concept  correct_answer        question  \
0   0  2022-11-23T04:58:07+00:00        1               3  What is 11*11?   
1   1  2022-11-23T04:57:33+00:00        1               1   What is 3*12?   
2   2  2022-11-23T04:53:47+00:00        0               2  What is 11+12?   
3   3  2022-11-20T03:26:31+00:00        0               1  What is 2 + 4?   
4   4  2022-11-27T22:48:07+00:00        2               2         2x = 20   

                          answers  
0               [90, 11, 13, 121]  
1               [312, 36, 48, 12]  
2              [1112, 13, 23, 33]  
3                   [24, 6, 4, 2]  
4  [x = 2, x = 20, x = 10, x = 5]

In [93]:
concepts = supabase.table("concepts").select("*").execute()
concepts = json.loads(concepts.json())
concepts = pd.DataFrame(concepts["data"])

print(concepts.shape)
concepts.head()

(3, 3)


id                 created_at            name
0   0  2022-11-15T17:08:53+00:00        addition
1   1  2022-11-23T04:57:00+00:00  multiplication
2   2  2022-11-27T22:47:07+00:00       equations

In [94]:
for i, row in questions.iterrows():
    interactions = data[data["question_id"] == row["id"]]
    sum_correct = 0

    for j, interaction in interactions.iterrows():
        if interaction["answered_correctly"] == 1:
            sum_correct += 1

    questions.at[i, "difficulty"] = sum_correct / len(interactions)

print(questions.shape)
questions.head()

(10, 7)


id                 created_at  concept  correct_answer        question  \
0   0  2022-11-23T04:58:07+00:00        1               3  What is 11*11?   
1   1  2022-11-23T04:57:33+00:00        1               1   What is 3*12?   
2   2  2022-11-23T04:53:47+00:00        0               2  What is 11+12?   
3   3  2022-11-20T03:26:31+00:00        0               1  What is 2 + 4?   
4   4  2022-11-27T22:48:07+00:00        2               2         2x = 20   

                          answers  difficulty  
0               [90, 11, 13, 121]       0.500  
1               [312, 36, 48, 12]       0.625  
2              [1112, 13, 23, 33]       0.375  
3                   [24, 6, 4, 2]       1.000  
4  [x = 2, x = 20, x = 10, x = 5]       0.500

In [50]:
random.seed(42)
prev_user_id = interactions["user_id"].max()

while (len(data) < generate_until):
    concept_skills = {}
    user_id = prev_user_id + 1
    prev_user_id = user_id

    for i, row in concepts.iterrows():
        concept_skills[row["id"]] = random.uniform(0, 1)

    for i, row in questions.iterrows():
        concept_skill = concept_skills[row["concept"]]

        correct_prob = 0.25 + \
            (1 - 0.25) / \
            (1 + math.exp(-1 * concept_skill * row["difficulty"]))
        answered_correctly = 1 if random.random() < correct_prob else 0
        user_answer = row["correct_answer"] if answered_correctly == 1 else random.randint(
            0, 3)

        if answered_correctly == 0 and user_answer == row["correct_answer"]:
            while user_answer != row["correct_answer"]:
                user_answer = random.randint(0, 3)

        data = pd.concat([data, pd.DataFrame.from_records([{
            "id": 0,
            "user_id": user_id,
            "question_id": row["id"],
            "content_id": row["id"],
            "user_answer": user_answer,
            "answered_correctly": answered_correctly,
            "elapsed_time": random.randint(interactions["elapsed_time"].min(), interactions["elapsed_time"].max()),
            "concept_id": row["concept"],
        }])])

    if user_id % 500 == 0:
        print(f"Generated interactions for user {user_id}")


Generated interactions for user 500


In [95]:
data = data.sample(frac=1).reset_index(drop=True)
print(data.shape)
data.head(10000)

(39, 9)


id  user_id  question_id lecture_id  content_id  user_answer  \
0   1669589689963        0            7       None           7            0   
1   1669589741230        1            8       None           8            1   
2   1669588805469        0            2       None           2            0   
3   1669589681915        0            9       None           9            1   
4   1669588676588        0            1       None           1            2   
5   1669589702814        0            6       None           6            3   
6   1669179545274        0            0       None           0            3   
7   1669179618253        1            3       None           3            1   
8   1669179588565        1            0       None           0            2   
9   1669179559079        0            1       None           1            1   
10  1669179615250        1            2       None           2            2   
11  1669588700371        1            1       None           1            1   
12  1669588671010        0            2       None           2            2   
13  1669589758131        1            4       None           4            0   
14  1669589685531        0            8       None           8            2   
15  1669589762815        1            2       None           2            2   
16  1669589760481        1            3       None           3            1   
17  1669589765481        1            1       None           1            1   
18  1669588796203        0            3       None           3            1   
19  1669588695272        1            2       None           2            3   
20  1669589743780        1            7       None           7            0   
21  1669589717914        0            4       None           4            2   
22  1669589738514        1            9       None           9            1   
23  1669588663639        0            3       None           3            1   
24  1669589756629        1            5       None           5            0   
25  1669588809385        0            1       None           1            3   
26  1669588799803        0            3       None           3            1   
27  1669179578181        0            3       None           3            1   
28  1669589726431        0            2       None           2            3   
29  1669588690788        1            3       None           3            1   
30  1669589755198        1            6       None           6            0   
31  1669588822420        1            2       None           2            0   
32  1669589720496        0            3       None           3            1   
33  1669589729581        0            1       None           1            1   
34  1669589711297        0            5       None           5            2   
35  1669179605968        1            1       None           1            0   
36  1669588819420        1            3       None           3            1   
37  1669588824719        1            1       None           1            1   
38  1669179570936        0            2       None           2            0   

    answered_correctly  elapsed_time  concept_id  
0                    1             4           2  
1                    1             2           0  
2                    0             5           0  
3                    1             4           1  
4                    0             5           1  
5                    0            12           2  
6                    1            17           1  
7                    1             2           0  
8                    0             5           1  
9                    1            13           1  
10                   1             9           0  
11                   1             4           1  
12                   1             7           0  
13                   0             1           2  
14                   0             3           0  
15                   1             2  

In [96]:
val_size = int(data.shape[0] * 0.2)

val = data[-val_size:]
train = data[:-val_size]

In [98]:
train_dict = {}
val_dict = {}

for i, row in train.iterrows():
    if row["user_id"] not in train_dict:
        train_dict[row["user_id"]] = [
            0,
            [],
            [],
            []
        ]
    train_dict[row["user_id"]][0] += 1
    train_dict[row["user_id"]][1].append(int(row["concept_id"]))
    train_dict[row["user_id"]][2].append(int(row["question_id"]))
    if int(row["answered_correctly"]) == 1:
        train_dict[row["user_id"]][3].append(53331)
    else:
        train_dict[row["user_id"]][3].append(53330)

for i, row in val.iterrows():
    if row["user_id"] not in val_dict:
        val_dict[row["user_id"]] = [
            0,
            [],
            [],
            []
        ]
    val_dict[row["user_id"]][0] += 1
    val_dict[row["user_id"]][1].append(int(row["concept_id"]))
    val_dict[row["user_id"]][2].append(int(row["question_id"]))
    if int(row["answered_correctly"]) == 1:
        val_dict[row["user_id"]][3].append(53331)
    else:
        val_dict[row["user_id"]][3].append(53330)

In [100]:
val_dict

{0: [4, [0, 1, 2, 0], [3, 1, 5, 2], [53331, 53331, 53330, 53330]],
 1: [3, [1, 0, 1], [1, 3, 1], [53330, 53331, 53331]]}

In [101]:
train_path = "data/custom/custom_train.csv"
val_path = "data/custom/custom_test.csv"

with open(train_path, "w") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_NONE,
                        escapechar=" ", delimiter=" ")

    for key in train_dict:
        arr = train_dict[key]

        for data in arr:
            if type(data) == list:
                writer.writerow([",".join([str(x) for x in data])])
            else:
                writer.writerow([data])

with open(val_path, "w") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_NONE,
                        escapechar=" ", delimiter=" ")

    for key in val_dict:
        arr = val_dict[key]

        for data in arr:
            if type(data) == list:
                writer.writerow([",".join([str(x) for x in data])])
            else:
                writer.writerow([data])


In [102]:
skill_matrix = np.zeros((len(concepts), len(concepts)), dtype=int)

for i, row in concepts.iterrows():
    skill_matrix[i][i] = 1

print(skill_matrix)

np.savetxt("data/custom/custom_skill_matrix.txt", skill_matrix, delimiter=" ", fmt="%d")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
